namespace KafkaRestProducer.Tests.Kafka;

using FluentAssertions;
using KafkaRestProducer.Kafka;
using KafkaRestProducer.Models;
using KafkaRestProducer.Wrappers;
using Moq;
using Newtonsoft.Json.Linq;
using Xunit;

public class MessageSerializerTests
{
    private readonly Mock<IAssemblyWrapper> assemblyWrapperMock;
    private readonly MessageSerializer messageSerializer;

    public MessageSerializerTests()
    {
        this.assemblyWrapperMock = new Mock<IAssemblyWrapper>();
        this.messageSerializer = new MessageSerializer(assemblyWrapperMock.Object);
    }

    [Fact]
    public void OnSingleSerialize_WithJsonSerializer_ShouldReturnJsonObject()
    {
        // Arrange
        const bool autoGeneratePayload = false;

        var messageRequest = new MessageRequest
        {
            Serializer = SerializerType.Json,
            Payload = new
            {
                Id = 1,
                Name = "SomeOne"
            }
        };

        // Act
        var result = this.messageSerializer.Serialize(
            messageRequest,
            autoGeneratePayload);

        // Assert
        result.Should().NotBeNull();
        result.Should().BeOfType<JObject>();
    }

    [Fact]
    public void OnSingleSerialize_WithProtobufSerializerAndCustomPayload_ShouldReturnObject()
    {
        // Arrange
        const bool autoGeneratePayload = false;

        var messageRequest = new MessageRequest
        {
            Serializer = SerializerType.Protobuf,
            Contract = "FakeContract",
            Payload = new
            {
                Id = 1,
                Name = "SomeOne",
                Addresses = new List<string> { "street1", "street2" }
            }
        };

        this.assemblyWrapperMock
            .Setup(x => x.GetType(It.Is<string>(s => s == messageRequest.Contract)))
            .Returns(typeof(FakeContract))
            .Verifiable();

        // Act
        var result = this.messageSerializer.Serialize(
            messageRequest,
            autoGeneratePayload);

        // Assert
        this.assemblyWrapperMock.Verify();
        result.Should().NotBeNull();
        result.Should().BeOfType<FakeContract>();

        var fakeContract = new FakeContract
        {
            Id = 1,
            Name = "SomeOne",
        };

        fakeContract.AddAddress("street1");
        fakeContract.AddAddress("street2");

        ((FakeContract)result).Should().BeEquivalentTo(fakeContract);
    }

    [Fact]
    public void OnSingleSerialize_WithProtobufSerializerAndAutoGeneratedPayload_ShouldReturnObject()
    {
        // Arrange
        const bool autoGeneratePayload = true;

        var messageRequest = new MessageRequest
        {
            Serializer = SerializerType.Protobuf,
            Contract = "FakeContract"
        };

        this.assemblyWrapperMock
            .Setup(x => x.GetType(It.Is<string>(s => s == messageRequest.Contract)))
            .Returns(typeof(FakeContract))
            .Verifiable();

        // Act
        var result = this.messageSerializer.Serialize(
            messageRequest,
            autoGeneratePayload);

        // Assert
        this.assemblyWrapperMock.Verify();
        result.Should().NotBeNull();
        result.Should().BeOfType<FakeContract>();
    }

    [Fact]
    public void OnSingleSerialize_WithAvroSerializerAndCustomPayload_ShouldReturnObject()
    {
        // Arrange
        const bool autoGeneratePayload = false;

        var messageRequest = new MessageRequest
        {
            Serializer = SerializerType.Avro,
            Contract = "FakeContract",
            Payload = new
            {
                Id = 1,
                Name = "SomeOne"
            }
        };

        this.assemblyWrapperMock
            .Setup(x => x.GetType(It.Is<string>(s => s == messageRequest.Contract)))
            .Returns(typeof(FakeContract))
            .Verifiable();

        // Act
        var result = this.messageSerializer.Serialize(
            messageRequest,
            autoGeneratePayload);

        // Assert
        this.assemblyWrapperMock.Verify();
        result.Should().NotBeNull();
        result.Should().BeOfType<FakeContract>();
    }

    [Fact]
    public void OnSingleSerialize_WithAvroSerializerAndAutoGeneratedPayload_ShouldReturnObject()
    {
        // Arrange
        const bool autoGeneratePayload = true;
        
        var messageRequest = new MessageRequest
        {
            Serializer = SerializerType.Avro,
            Contract = "FakeContract"
        };

        this.assemblyWrapperMock
            .Setup(x => x.GetType(It.Is<string>(s => s == messageRequest.Contract)))
            .Returns(typeof(FakeContract))
            .Verifiable();

        // Act
        var result = this.messageSerializer.Serialize(
            messageRequest,
            autoGeneratePayload);

        // Assert
        this.assemblyWrapperMock.Verify();
        result.Should().NotBeNull();
        result.Should().BeOfType<FakeContract>();
    }

    [Fact]
    public void OnBulkSerialize_ShouldReturnListOfObjects()
    {
        // Arrange
        var messageRequestBulk = new MessageRequestBulk
        {
            Serializer = SerializerType.Avro,
            Contract = "FakeContract",
            NumberOfMessages = 15
        };

        this.assemblyWrapperMock
            .Setup(x => x.GetType(It.IsAny<string>()))
            .Returns(typeof(FakeContract))
            .Verifiable();

        // Act
        var result = this.messageSerializer.BulkSerialize(messageRequestBulk);

        // Assert
        this.assemblyWrapperMock.Verify();
        result.Should().HaveCount(messageRequestBulk.NumberOfMessages);
        result.Select(x => x.GetType()).Should().AllBeOfType<FakeContract>();
    }
}

public class FakeContract
{
    private readonly List<string> addresses;

    public int Id { get; set; } = 1;

    public string Name { get; set; } = string.Empty;

    public List<string> Addresses { get; } = new List<string>();

    public void AddAddress(string address)
    {
        this.Addresses.Add(address);
    }
}
