version: '3.4'

services:
  build:
    image: marcosandremartins/rest-producer:${RELEASE_VERSION}
    build:
      context: .
      dockerfile: Dockerfile
      target: final
      args:
        RELEASE_VERSION: ${RELEASE_VERSION}

  sdkbuild:
    image: marcosandremartins/rest-producer-with-sdk:${RELEASE_VERSION}
    build:
      context: .
      dockerfile: Dockerfile
      target: sdkfinal
      args:
        RELEASE_VERSION: ${RELEASE_VERSION}

  tests:
    image: marcosandremartins/rest-producer-tests:${RELEASE_VERSION}
    build:
      context: .
      dockerfile: Dockerfile
      target: tests
      args:
        RELEASE_VERSION: ${RELEASE_VERSION}

  zookeeper:
    image: confluentinc/cp-zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_SCHEMA_REGISTRY_URL: "schemaregistry:8081"
    depends_on:
      - zookeeper

  schemaregistry:
    image: confluentinc/cp-schema-registry
    ports:
      - "8081:8081"
    environment:
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: "PLAINTEXT://kafka:29092"
      SCHEMA_REGISTRY_HOST_NAME: schemaregistry
      SCHEMA_REGISTRY_LISTENERS: "http://0.0.0.0:8081"
    depends_on:
      - zookeeper

networks:
  default:
    driver: bridge
