name: Build

on:
  pull_request:

  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0

      - name: GITHUB CONTEXT
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

      - name: Commit Lint
        uses: wagoid/commitlint-github-action@master
        with:
          failOnWarnings: true

      - name: Setup .NET
        uses: actions/setup-dotnet@v4.1.0
        with:
          dotnet-version: '8.0.x'

      - name: Build
        run: dotnet build KafkaRestProducer.sln -c Release

      - name: UnitTest
        run: |
          dotnet test src/KafkaRestProducer.Tests/KafkaRestProducer.Tests.csproj -c Release --logger "console;verbosity=detailed"

      - name: IntegrationTest
        run: |
          dotnet test src/KafkaRestProducer.IntegrationTests/KafkaRestProducer.IntegrationTests.csproj -c Release --logger "console;verbosity=detailed"
